version: '3'

services:
  discord-rss-bot:
    build: .
    container_name: discord-rss-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    networks:
      - bot-network
  #     - bot-network

networks:
  bot-network:
    driver: bridge

