version: '3'

services:
  discord-rss-bot:
    build: .
    container_name: discord-rss-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    networks:
      - bot-network

  # LM Studio API（オプション）
  # lmstudio-api:
  #   image: lmstudio/api:latest
  #   container_name: lmstudio-api
  #   restart: unless-stopped
  #   ports:
  #     - "1234:1234"
  #   volumes:
  #     - ./models:/models
  #   environment:
  #     - MODEL_PATH=/models/your-model.gguf
  #   networks:
  #     - bot-network

networks:
  bot-network:
    driver: bridge

